"""
OpenCode Agent Slack Bridge
Slack @mention → OpenCode serve API → Agent → Slack thread reply
Auto-generated by slack-opencode-bridge-factory skill
"""

import os
import re
import json
import logging
import threading
import requests
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler

import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from session_store import (
    get_session,
    save_session,
    touch_session,
    cleanup_old_sessions,
    increment_depth,
    reset_depth,
)

# ── 설정 ──────────────────────────────────────────────
OPENCODE_URL = os.environ.get("OPENCODE_URL", "http://localhost:4096")
SLACK_BOT_TOKEN = os.environ.get("SLACK_BOT_TOKEN", "")
SLACK_APP_TOKEN = os.environ.get("SLACK_APP_TOKEN", "")
SLACK_OWNER_ID = os.environ.get("SLACK_OWNER_ID", "")
ALLOWED_USERS = {uid.strip() for uid in SLACK_OWNER_ID.split(",") if uid.strip()}
ALLOWED_PEER_BOT_USERS = {
    u.strip()
    for u in os.environ.get("ALLOWED_PEER_BOT_USERS", "").split(",")
    if u.strip()
}
AGENT_DEPTH_LIMIT = int(os.environ.get("AGENT_DEPTH_LIMIT", "10"))
SSE_TIMEOUT = 600
SLACK_MAX_LEN = 3800

# ── 로깅 ──────────────────────────────────────────────
_log_path = os.environ.get(
    "BRIDGE_LOG_PATH",
    os.path.expanduser("~/.local/log/opencode-bridges/bridge/bridge.log"),
)
os.makedirs(os.path.dirname(_log_path), exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler(_log_path),
    ],
)
log = logging.getLogger(__name__)

# ── Slack App ─────────────────────────────────────────
app = App(token=SLACK_BOT_TOKEN, token_verification_enabled=False)


# ── OpenCode API 헬퍼 ─────────────────────────────────


def create_opencode_session() -> str:
    resp = requests.post(f"{OPENCODE_URL}/session", json={}, timeout=30)
    resp.raise_for_status()
    session_id = resp.json()["id"]
    log.info(f"Created OpenCode session: {session_id}")
    return session_id


def send_prompt(session_id: str, text: str) -> None:
    payload = {
        "agent": os.environ.get("OPENCODE_AGENT", "build"),
        "parts": [{"type": "text", "text": text}],
    }
    resp = requests.post(
        f"{OPENCODE_URL}/session/{session_id}/prompt_async",
        json=payload,
        timeout=30,
    )
    resp.raise_for_status()
    log.info(f"Sent prompt to session {session_id}")


def collect_response(session_id: str) -> str:
    """
    SSE /event 스트림에서 해당 세션의 응답 텍스트를 수집.
    session.idle 이벤트가 오면 완료.
    """
    text_parts: dict[str, str] = {}
    error_msg: str | None = None

    try:
        with requests.get(
            f"{OPENCODE_URL}/event",
            stream=True,
            timeout=SSE_TIMEOUT,
        ) as resp:
            resp.raise_for_status()
            resp.encoding = "utf-8"
            for line in resp.iter_lines(decode_unicode=True):
                if not line or not line.startswith("data:"):
                    continue
                try:
                    event = json.loads(line[5:].strip())
                except json.JSONDecodeError:
                    continue

                etype = event.get("type", "")
                props = event.get("properties", {})

                if props.get("sessionID") and props["sessionID"] != session_id:
                    continue

                if etype == "message.part.delta" and props.get("field") == "text":
                    part_id = props.get("partID", "default")
                    text_parts[part_id] = text_parts.get(part_id, "") + props.get(
                        "delta", ""
                    )

                elif etype == "session.error":
                    err = props.get("error", {})
                    error_msg = err.get("data", {}).get("message") or err.get(
                        "name", "Unknown error"
                    )
                    log.error(f"Session error: {error_msg}")

                elif etype == "session.idle":
                    log.info(f"Session {session_id} idle — response complete")
                    break

    except requests.Timeout:
        log.error(f"SSE timeout after {SSE_TIMEOUT}s for session {session_id}")
        return "처리 시간이 초과되었습니다. (10분 제한)"
    except Exception as e:
        log.error(f"SSE error: {e}")
        return f"응답 수신 중 오류가 발생했습니다: {e}"

    if error_msg:
        return f"에이전트 오류: {error_msg}"

    full_text = "".join(text_parts.values()).strip()
    return full_text or "(응답 없음)"


def chunk_text(text: str, max_len: int = SLACK_MAX_LEN) -> list[str]:
    """
    텍스트를 Slack 메시지 길이 제한에 맞게 분할.
    문단(\\n\\n) 또는 줄바꿈(\\n) 기준으로 자연스럽게 분할.
    """
    if len(text) <= max_len:
        return [text]

    chunks = []
    while text:
        if len(text) <= max_len:
            chunks.append(text)
            break
        split_at = text.rfind("\n\n", 0, max_len)
        if split_at == -1:
            split_at = text.rfind("\n", 0, max_len)
        if split_at == -1:
            split_at = text.rfind(" ", 0, max_len)
        if split_at == -1:
            split_at = max_len
        chunks.append(text[:split_at].strip())
        text = text[split_at:].strip()

    return [c for c in chunks if c]


# ── 메인 핸들러 ───────────────────────────────────────


def process_mention(
    text: str, thread_ts: str, channel: str, say, pending_ts: str | None = None
) -> None:
    try:
        current_depth = increment_depth(thread_ts)
        if current_depth > AGENT_DEPTH_LIMIT:
            warning_msg = f"⚠️ 에이전트 응답 체인 한도({AGENT_DEPTH_LIMIT}) 초과. 체인을 중단합니다. (depth={current_depth})"
            if pending_ts:
                try:
                    app.client.chat_delete(channel=channel, ts=pending_ts)
                except Exception:
                    pass
            say(text=warning_msg, thread_ts=thread_ts)
            return

        session_id = get_session(thread_ts)
        if session_id:
            log.info(f"Reusing session {session_id} for thread {thread_ts}")
            touch_session(thread_ts)
        else:
            session_id = create_opencode_session()
            save_session(thread_ts, session_id)
            log.info(f"New session {session_id} for thread {thread_ts}")

        send_prompt(session_id, text)
        response = collect_response(session_id)

        chunks = chunk_text(response)
        # Slack chat.update has 3001-char limit; chat.postMessage allows 40000 — delete placeholder then post
        if pending_ts:
            try:
                app.client.chat_delete(channel=channel, ts=pending_ts)
            except Exception as e:
                log.warning(f"Could not delete pending message: {e}")
        for i, chunk in enumerate(chunks):
            say(text=chunk, thread_ts=thread_ts)
            log.info(f"Sent chunk {i + 1}/{len(chunks)} to thread {thread_ts}")

    except requests.ConnectionError:
        log.error("Cannot connect to OpenCode serve")
        err = "에이전트 연결 실패. opencode serve가 실행 중인지 확인해주세요."
        if pending_ts:
            app.client.chat_update(channel=channel, ts=pending_ts, text=err)
        else:
            say(text=err, thread_ts=thread_ts)
    except Exception as e:
        log.error(f"Unexpected error in process_mention: {e}", exc_info=True)
        err = f"처리 중 오류가 발생했습니다: {e}"
        if pending_ts:
            app.client.chat_update(channel=channel, ts=pending_ts, text=err)
        else:
            say(text=err, thread_ts=thread_ts)


@app.event("app_mention")
def handle_mention(event, say):
    user_id = event.get("user", "")

    if (
        ALLOWED_USERS
        and user_id not in ALLOWED_USERS
        and user_id not in ALLOWED_PEER_BOT_USERS
    ):
        log.warning(f"Unauthorized mention from user {user_id} — ignoring")
        return

    raw_text = event.get("text", "")
    text = re.sub(r"<@\w+>", "", raw_text).strip()

    if not text:
        say(text="명령을 입력해주세요.", thread_ts=event.get("thread_ts", event["ts"]))
        return

    thread_ts = event.get("thread_ts", event["ts"])
    channel = event["channel"]

    log.info(f"Mention from {user_id} in {channel}/{thread_ts}: {text[:80]}")

    pending = say(text="처리 중...", thread_ts=thread_ts)
    pending_ts = pending.get("ts") if pending else None

    t = threading.Thread(
        target=process_mention,
        args=(text, thread_ts, channel, say, pending_ts),
        daemon=True,
    )
    t.start()


@app.event("message")
def handle_thread_message(event, say, context):
    if event.get("subtype"):
        return
    my_bot_user_id = context.get("bot_user_id", "")
    if event.get("user") == my_bot_user_id:
        return

    thread_ts = event.get("thread_ts")
    if not thread_ts:
        return

    bot_user_id = context.get("bot_user_id", "")
    raw_text = event.get("text", "")
    if bot_user_id and f"<@{bot_user_id}>" in raw_text:
        return

    session_id = get_session(thread_ts)
    if not session_id:
        return

    user_id = event.get("user", "")
    if (
        ALLOWED_USERS
        and user_id not in ALLOWED_USERS
        and user_id not in ALLOWED_PEER_BOT_USERS
    ):
        return

    text = re.sub(r"<@\w+>", "", raw_text).strip()
    if not text:
        return

    log.info(
        f"Thread reply from {user_id} in {event['channel']}/{thread_ts}: {text[:80]}"
    )

    pending = say(text="처리 중...", thread_ts=thread_ts)
    pending_ts = pending.get("ts") if pending else None

    t = threading.Thread(
        target=process_mention,
        args=(text, thread_ts, event["channel"], say, pending_ts),
        daemon=True,
    )
    t.start()


# ── 진입점 ────────────────────────────────────────────

if __name__ == "__main__":
    if not SLACK_BOT_TOKEN:
        log.error("SLACK_BOT_TOKEN not set")
        raise SystemExit(1)
    if not SLACK_APP_TOKEN:
        log.error("SLACK_APP_TOKEN not set")
        raise SystemExit(1)

    # Clean up stale sessions on startup
    try:
        cleaned = cleanup_old_sessions(days=30)
        if cleaned > 0:
            log.info(f"Cleaned up {cleaned} stale sessions")
    except Exception as e:
        log.warning(f"Session cleanup failed (non-fatal): {e}")

    log.info(
        f"Starting OpenCode Bridge (agent: {os.environ.get('AGENT_NAME', 'unknown')})..."
    )
    log.info(f"OpenCode URL: {OPENCODE_URL}")
    log.info(f"Allowed users: {ALLOWED_USERS or '(all — SLACK_OWNER_ID not set)'}")
    log.info(f"Depth limit: {AGENT_DEPTH_LIMIT}")
    log.info(f"Peer bot users: {ALLOWED_PEER_BOT_USERS or '(none)'}")

    handler = SocketModeHandler(app, SLACK_APP_TOKEN)
    handler.start()
